Support arbitrary UIDs for OpenShift

diff --git a/coreos-assembler b/coreos-assembler
--- a/coreos-assembler
+++ b/coreos-assembler
@@ -7,6 +7,16 @@ set -euo pipefail
 # docker/podman don't run through PAM, but we want this set
 export USER=${USER:-$(id -nu)}
 
+# When trying to connect to libvirt we get "Failed to find user record
+# for uid" errors if there is no entry for our UID in /etc/passwd.
+# This was taken from 'Support Arbitrary User IDs' section of:
+#   https://docs.openshift.com/container-platform/3.10/creating_images/guidelines.html
+if ! whoami &> /dev/null; then
+  if [ -w /etc/passwd ]; then
+      echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
+  fi
+fi
+
 # Ensure we've unshared our mount namespace so
 # the later umount doesn't affect the host potentially
 if [ -e /sys/fs/selinux/status ]; then
