kola: Do failed units/SELinux checks both before *and* after tests
First: Revert "Revert "kola: Add --no-default-checks""
 (this reverts commit: 57b3520ab1cefaab9b872d0f2f8dce04668dfbff )

Now, when I went to add the SELinux denials check, I completely missed
that we only were checking for denials *before* the test runs.

We obviously want to check both before and after - the same
way we do with e.g. looking for errors on the console.

As part of this, I'd also added `--no-default-checks` but it
actually didn't work.  Fix that so that it does work, and add
a test case with a failing systemd unit that verifies this,
so we can test the test system.

In order to help ratchet things, also add a special `default-checks`
entry to the denylist.  This way if e.g. we are hitting SELinux AVC
denials just on one arch/test we can turn them off temporarily.

diff --git a/ci/run-kola-self-tests b/ci/run-kola-self-tests
--- a/ci/run-kola-self-tests
+++ b/ci/run-kola-self-tests
@@ -3,6 +3,20 @@ set -euo pipefail
 dn=$(cd $(dirname $0) && pwd)
 toplevel=$(cd ${dn} && git rev-parse --show-toplevel)
 set -x
+# Unit failure
+if cosa kola run --output-dir tmp/kolaself -E ${toplevel}/tests/kola-ci-unit-failure 'ext.kola-ci*' |& tee tmp/err.txt; then
+    echo "expected kola-ci-unit-failure to fail" 1>&2
+    exit 1
+fi
+if ! grep -qF 'failed basic checks' tmp/err.txt; then
+    echo "Missing expected failed basic checks error" 1>&2
+    exit 1
+fi
+# And this run should pass
+cosa kola run --output-dir tmp/kolaself -E ${toplevel}/tests/kola-ci-unit-failure 'ext.kola-ci*' --no-default-checks
+
+rm tmp/kolaself -rf
+
 cosa kola run --output-dir tmp/kolaself -E ${toplevel}/tests/kola-ci-self 'ext.kola-ci-self*' "$@"
 log=$(find tmp/kolaself -type f -name kola-runext-autopkgtest-reboot.txt)
 test -n "${log}"
