cmd-fetch: support "autolocking" from an arch build
In a multi-arch build, we want to be able to provide some guarantees
that the RPM set across arches is the same (of course, save for any
arch-specific packages). The canonical way to do this is with lockfiles,
but RHCOS currently doesn't have that. However, since we currently build
x86_64 before building the multi-arch variants, what we can do is derive
a lockfile from the x86_64 build and use that in the multi-arch builds.
This patch adds a new "autolock" feature to the `fetch` and `build`
commands to do just that.

Even once RHCOS gets lockfiles, this will also be useful for development
streams where we purposely don't want to maintain lockfiles (such as
rawhide).

This isn't foolproof. Notably if a package is included in more than one
multi-arch build, but not x86_64, it's possible for that package to
diverge. Presently in RHCOS 4.13 at least, only one such package exists
(`libatomic`), so in practice that risk is quite low.

diff --git a/src/cmd-fetch b/src/cmd-fetch
--- a/src/cmd-fetch
+++ b/src/cmd-fetch
@@ -31,10 +31,12 @@ Usage: coreos-assembler fetch --help
   --update-lockfile        Update base lockfile to latest packages
   --write-lockfile-to=FILE Write updated base lockfile to separate file
   --with-cosa-overrides    Don't ignore cosa overrides in `overrides/rpm`
+  --autolock=VERSION       If no base lockfile used, create one from any arch build of `VERSION`
 
 EOF
 }
 
+AUTOLOCK_VERSION=
 UPDATE_LOCKFILE=
 OUTPUT_LOCKFILE=
 IGNORE_COSA_OVERRIDES_ARG=--ignore-cosa-overrides
@@ -42,7 +44,7 @@ DRY_RUN=
 FORCE_ARG=
 STRICT=
 rc=0
-options=$(getopt --options h --longoptions help,update-lockfile,dry-run,with-cosa-overrides,write-lockfile-to:,strict,force -- "$@") || rc=$?
+options=$(getopt --options h --longoptions help,update-lockfile,dry-run,with-cosa-overrides,write-lockfile-to:,strict,force,autolock: -- "$@") || rc=$?
 [ $rc -eq 0 ] || {
     print_help
     exit 1
@@ -74,6 +76,10 @@ while true; do
         --force)
             FORCE_ARG=--force-nocache
             ;;
+        --autolock)
+            shift;
+            AUTOLOCK_VERSION=$1
+            ;;
         --)
             shift
             break
@@ -96,6 +102,20 @@ prepare_build
 
 lock_args=
 extra_args=
+
+# Apply autolock from another build for this version if no base lockfile
+# exists. Do this before so that overrides come after.
+if  [ -n "${AUTOLOCK_VERSION}" ]; then
+    if [ -f "${manifest_lock}" ]; then
+        fatal "ERROR: Requested --autolock, but base lockfile found"
+    fi
+    autolockfile=$(generate_autolock "${AUTOLOCK_VERSION}")
+    if [ -z "${autolockfile}" ]; then
+        fatal "ERROR: Requested --autolock, but no generated lockfile found"
+    fi
+    lock_args+=" --ex-lockfile=${autolockfile}"
+fi
+
 if [ -n "${UPDATE_LOCKFILE}" ]; then
     # Put this under tmprepo so it gets automatically chown'ed if needed
     extra_args+=" --ex-write-lockfile-to=${tmprepo}/tmp/manifest-lock.json"
@@ -120,6 +140,12 @@ if [ -n "${DRY_RUN}" ]; then
 fi
 
 if [ -n "${STRICT}" ]; then
+    if [ -n "${AUTOLOCK_VERSION}" ]; then
+        # They're theoretically independent, but in practice it's unlikely
+        # that an autolockfile will include all the packages needed to satisfy
+        # --strict. So let's just catch it early.
+        fatal "ERROR: Can't use --autolock and --strict together"
+    fi
     extra_args+=" --ex-lockfile-strict"
 fi
 
