Delay check on default manifest and image files until we know they're being used.
The default manifest.yaml and image.yaml were checked to confirm they exist before it was
even known whether they were the right files to use or not.  Move the check to occur after
we know we're not using a VARIANT that points to different files.

diff --git a/src/cmd-init b/src/cmd-init
--- a/src/cmd-init
+++ b/src/cmd-init
@@ -179,10 +179,6 @@ mkdir -p src
 # Default paths for manifest.yaml & image.yaml
 manifest="src/config/manifest.yaml"
 image="src/config/image.yaml"
-if [[ ! -f "${manifest}" ]] || [[ ! -f "${image}" ]]; then
-    echo 1>&2 "Could not find default manifests (${manifest} & ${image})"
-    fatal "If you are using a custom configuration, be sure it has a manifest.yaml & image.yaml."
-fi
 
 # Select the variant if requested
 if [[ -n "${VARIANT}" ]] && [[ "${VARIANT}" != "default" ]]; then
@@ -197,6 +193,9 @@ if [[ -n "${VARIANT}" ]] && [[ "${VARIANT}" != "default" ]]; then
   "coreos-assembler.config-variant": "${VARIANT}"
 }
 EOF
+elif [[ ! -f "${manifest}" ]] || [[ ! -f "${image}" ]]; then
+    echo 1>&2 "Could not find default manifests (${manifest} & ${image})"
+    fatal "If you are using a custom configuration, be sure it has a manifest.yaml & image.yaml."
 fi
 
 mkdir -p cache
