Move OSTree commit into build directory
Rather than keeping OSTree data separately in the toplevel `repo/`, make
it part of the build directory. This solves a bunch of issues and makes
things conceptually clearer.

See discussions in:
https://github.com/coreos/coreos-assembler/issues/159

diff --git a/src/cmd-build b/src/cmd-build
--- a/src/cmd-build
+++ b/src/cmd-build
@@ -79,14 +79,36 @@ if [ -L "${workdir}"/builds/latest ]; then
 fi
 
 previous_commit=
-if [ -n "${ref:-}" ]; then
-    previous_commit=$(ostree --repo="${workdir}"/repo rev-parse "${ref}" 2>/dev/null || true)
-fi
-# If the ref was unset or missing, look at the previous build
-if [ -z "${previous_commit}" ] && [ -n "${previous_build}" ]; then
+if [ -n "${previous_build}" ]; then
     previous_commit=$(jq -r '.["ostree-commit"]' < "${previous_builddir}/meta.json")
 fi
 echo "Previous commit: ${previous_commit:-none}"
+
+if [ -n "${previous_commit}" ]; then
+    # If we don't have the previous commit (or it's partial), then try to
+    # re-import it; this saves us recompression time later on since it's likely
+    # a lot of the new objects in this build will be the same.
+    commitpath=${tmprepo}/objects/${previous_commit::2}/${previous_commit:2}.commit
+    commitpartial=${tmprepo}/state/${previous_commit}.commitpartial
+    if [ ! -f "${commitpath}" ] || [ -f "${commitpartial}" ]; then
+        if [ -f "${previous_builddir}/ostree-commit.tar" ]; then
+            mkdir tmp/prev_repo
+            tar -C tmp/prev_repo -xf "${previous_builddir}/ostree-commit.tar"
+            ostree pull-local --repo="${tmprepo}" tmp/prev_repo "${previous_commit}"
+            rm -rf tmp/prev_repo
+        else
+            # ok, just fallback to importing the commit object only
+            mkdir -p "$(dirname "${commitpath}")"
+            cp "${previous_builddir}/ostree-commit-object" "${commitpath}"
+            touch "${commitpartial}"
+        fi
+    fi
+
+    # and point the ref to it if there isn't one already (in which case it might be newer, but e.g. Anaconda failed)
+    if ! ostree rev-parse --repo="${tmprepo}" "${ref}" &>/dev/null; then
+        ostree refs --repo="${tmprepo}" --create "${ref}" "${previous_commit}"
+    fi
+fi
 
 # Calculate image input checksum now and gather previous image build variables if any
 ks_path="${configdir}"/image.ks
@@ -125,8 +147,6 @@ composejson=${PWD}/tmp/compose.json
 # --cache-only is here since `fetch` is a separate verb.
 runcompose --cache-only ${FORCE} --add-metadata-from-json "${commitmeta_input_json}" \
            --write-composejson-to "${composejson}"
-# Always update the summary, since we used to do so
-ostree --repo="${workdir}/repo" summary -u
 # Very special handling for --write-composejson-to as rpm-ostree doesn't
 # write it if the commit didn't change.
 if [ -f "${changed_stamp}" ]; then
@@ -136,7 +156,10 @@ if [ -f "${changed_stamp}" ]; then
     # Save this in case the image build fails
     cp -a --reflink=auto "${composejson}" "${workdir}"/tmp/compose-"${commit}".json
 else
-    commit=${previous_commit}
+    # Pick up from tmprepo; that's what rpm-ostree is comparing against. It may
+    # be the same as previous_commit, or newer if a previous build failed image
+    # creation.
+    commit=$(ostree rev-parse --repo="${tmprepo}" "${ref}")
     image_input_checksum=$( (echo "${commit}" && echo "${image_config_checksum}") | sha256sum_str)
     # Note we may not actually have a previous build in the case of
     # successfully composing an ostree but failing the image on the
@@ -148,7 +171,7 @@ else
 
     # Grab the previous treecompose JSON (local developer case: treecompose succeeded but
     # image build failed) if possible, otherwise grab the previous build
-    cached_previous_composejson="${workdir}"/tmp/compose-"${previous_commit}".json
+    cached_previous_composejson=${workdir}/tmp/compose-${commit}.json
     if [ -f "${cached_previous_composejson}" ]; then
         echo "Resuming partial build from: ${commit}"
         cp -a --reflink=auto "${cached_previous_composejson}" "${composejson}"
@@ -167,12 +190,17 @@ else
 fi
 
 if [ -n "${previous_build}" ]; then
-    rpm-ostree --repo="${workdir}"/repo db diff "${previous_commit}" "${commit}"
+    # do it once for the terminal
+    rpm-ostree --repo="${tmprepo}" db diff "${previous_commit}" "${commit}"
+    # and once more for the metadata, but only keep the pkgdiff key
+    rpm-ostree --repo="${tmprepo}" db diff --format=json \
+            "${previous_commit}" "${commit}" | \
+        jq '{pkgdiff: .pkgdiff}' > tmp/diff.json
 fi
 
 image_input_checksum=$( (echo "${commit}" && echo "${image_config_checksum}") | sha256sum_str)
 echo "New image input checksum: ${image_input_checksum}"
-version=$(ostree --repo="${workdir}"/repo show --print-metadata-key=version "${commit}" | sed -e "s,',,g")
+version=$(ostree --repo="${tmprepo}" show --print-metadata-key=version "${commit}" | sed -e "s,',,g")
 if [ "${previous_commit}" = "${commit}" ] && [ -n "${previous_image_genver:-}" ]; then
     image_genver=$((previous_image_genver + 1))
     buildid="${version}"-"${image_genver}"
@@ -192,10 +220,10 @@ img_base=tmp/${imageprefix}-base.qcow2
 checksum_location=$(find /usr/lib/coreos-assembler-anaconda/ -name '*CHECKSUM' | head -1)
 
 img_qemu=${imageprefix}-qemu.qcow2
-run_virtinstall "${workdir}/repo" "${ref}" "${PWD}"/"${img_base}" --variant=cloud
+run_virtinstall "${tmprepo}" "${ref}" "${PWD}"/"${img_base}" --variant=cloud
 /usr/lib/coreos-assembler/gf-platformid "$(pwd)"/"${img_base}" "$(pwd)"/"${img_qemu}" qemu
 
-"${dn}"/write-commit-object "${workdir}/repo" "${commit}" "$(pwd)"
+"${dn}"/write-commit-object "${tmprepo}" "${commit}" "$(pwd)"
 
 build_timestamp=$(date -u +$RFC3339)
 vm_iso_checksum=$(awk '/SHA256.*iso/{print$NF}' "${checksum_location}")
@@ -253,7 +281,7 @@ fi
 
 # Merge all the JSON; note that we want ${composejson} first
 # since we may be overriding data from a previous build.
-cat "${composejson}" tmp/meta.json tmp/images.json tmp/cosa-image.json "${commitmeta_input_json}" | jq -s add > meta.json
+cat "${composejson}" tmp/meta.json tmp/diff.json tmp/images.json tmp/cosa-image.json "${commitmeta_input_json}" | jq -s add > meta.json
 
 # Filter out `ref` if it's temporary
 if [ -n "${ref_is_temp}" ]; then
@@ -263,12 +291,29 @@ fi
 
 # And add the commit metadata itself, which includes notably the rpmdb pkglist
 # in a format that'd be easy to generate diffs out of for higher level tools
-"${dn}"/commitmeta_to_json "${workdir}/repo" "${commit}" > commitmeta.json
+"${dn}"/commitmeta_to_json "${tmprepo}" "${commit}" > commitmeta.json
+
+# And create the ostree repo tarball containing the commit
+if [ "${commit}" == "${previous_commit}" ]; then
+    cp -a --reflink=auto "${previous_builddir}/ostree-commit.tar" .
+else
+    ostree init --repo=repo --mode=archive
+    ostree pull-local --repo=repo "${tmprepo}" "${ref}"
+    if [ -n "${ref_is_temp}" ]; then
+        ostree refs --repo=repo --delete "${ref}"
+    fi
+    # Don't compress; archive repos are already compressed individually and we'd
+    # gain ~20M at best. We could probably have better gains if we compress the
+    # whole repo in bare/bare-user mode, but that's a different story...
+    tar -cf ostree-commit.tar -C repo .
+    rm -rf repo
+fi
 
 # Clean up our temporary data
 saved_build_tmpdir="${workdir}/tmp/last-build-tmp"
 rm -rf "${saved_build_tmpdir}"
 mv -T tmp "${saved_build_tmpdir}"
+ostree prune --repo="${tmprepo}" --refs-only
 # Back to the toplevel build directory, so we can rename this one
 cd "${workdir}"/builds
 # We create a .build-commit file to note that we're in the
